spring.application.name=LojaCarro

# Perfil ativo padrão (mude para 'prod' nas variáveis de ambiente do servidor)
spring.profiles.active=${SERVER:prod}

# Encoding UTF-8
spring.jpa.properties.hibernate.connection.charSet=UTF-8