# Banco de Dados Local (com fallback para valores padrões de dev)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/carros?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&useUnicode=yes&characterEncoding=UTF-8}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:erick}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:12345}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
server.port=8081
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true